"""add approval status to users

Revision ID: a39748b2e28d
Revises: 16421b2652a3
Create Date: 2026-09-07 00:18:15.562855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a39748b2e28d'
down_revision: Union[str, None] = '16421b2652a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    approval_enum = sa.Enum('pending', 'approved', 'rejected', name='approval_status_enum')
    approval_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('approval_status', approval_enum, server_default='approved', nullable=False))
    op.create_index(op.f('ix_users_approval_status'), 'users', ['approval_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_approval_status'), table_name='users')
    op.drop_column('users', 'approval_status')
    # ### end Alembic commands ###
